# Generated by Django 3.1.6 on 2022-05-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_auto_20220508_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaBatePapo',
        ),
    ]
